---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-triggerbinding
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositoryurl
    value: $(body.pull_request.head.repo.url)
  - name: contenttype
    value: $(header.Content-Type)